namespace: "netapp"
name: "elementsw"
version: "19.11.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "Apache-2.0"
readme: README.md
description: Netapp ElementSW (Solidfire) Collection
repository: https://github.com/ansible/ansible_collections_netapp
homepage: netapp.io