namespace: "netapp"
name: "elementsw"
version: "21.7.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: Netapp ElementSW (Solidfire) Collection
repository: https://github.com/ansible-collections/netapp.elementsw
issues: https://github.com/ansible-collections/netapp.elementsw/issues
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - netapp
    - solidfire
