namespace: "netapp"
name: "elementsw"
version: "20.01.0"
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
license: "GPL-2.0-or-later"
readme: README.md
description: Netapp ElementSW (Solidfire) Collection
repository: https://github.com/netapp/ansible/
homepage: netapp.io
tags:
    - storage
